name: Update .github
on:
  push:
    branches: ["main"]
jobs:
  git-sync:
    runs-on: ubuntu-latest
    if: github.repository == 'open-morphs/open-morphs'
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://github.com/open-morphs/.github'
          GIT_USERNAME: x-access-token
          GIT_PASSWORD: ${{ secrets.GH_PAT }}
